### ISSUE TITLE
Way to Move TrueNAS Secrets out of freenas-iscsi.yaml (values.yaml)?

### ISSUE THREAD

**Issue by reefland** [democratic-csi/charts#29]
Hi @travisghansen 

I'm deploying democratic-csi via ArgoCD and everything appears to be working fine.  While I'm using a Private Repository, I'm still looking for a way to move some items out of my `values.yaml` (`freenas-iscsi.yaml` is essentially my `values.yaml`) file so they are not checked into GitHub (or I'll store them in a Sealed Secret), such as `host` `apiKey` `username` `privateKey`.

Seems like I should be able to create a secret with these values prior to deployment and reference these within the `values.yaml`.

There is a `secrets` section:

```
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
#      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
#      # if doing CHAP
#      node-db.node.session.auth.authmethod: CHAP
#      node-db.node.session.auth.username: foo
#      node-db.node.session.auth.password: bar
#
#      # if doing mutual CHAP
#      node-db.node.session.auth.username_in: baz
#      node-db.node.session.auth.password_in: bar
    node-publish-secret:
    controller-expand-secret:
```

But it's not clear how something in `driver.config.httpConnection.apiKey` is mapped to something above???

Can't find a reference example on how this would work.
