### ISSUE TITLE
appVersion set to 1.0 for all helm releases

### ISSUE THREAD

**Issue by loeken** [democratic-csi/charts#44]
https://democratic-csi.github.io/charts/index.yaml

is there any reason why the appVersion is always set to 1.0 and doesnt have the actual version of the app?

**Comment by travisghansen** [comment]
Yeah I intentionally didn’t want to release a new version of the chart for every new version of the app.

**Comment by loeken** [comment]
I see you are setting your default image to always be "latest" 
```
  # democratic-csi controller
  driver:
    enabled: true
    image: docker.io/democraticcsi/democratic-csi:latest
```
so whatever helm chart version the user installs they would always end up with latest of democratic-csi unless specified in the values.yaml.
what i see most charts do is to define the default appVersion in chart.Yaml and leave the .Values.image.tag unset in the default values.yaml and something like this:
```
apiVersion: v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
```
to check if a .Values.image.tag is set and if not default to the chart's appVersion
