### ISSUE TITLE
Split image and tag into different values in the helm chart

### ISSUE THREAD

**Issue by ajchiarello** [democratic-csi/charts#56]
To make it simpler to use a local image repository for the images in the helm chart, please split the `image` values into separate `image` and `tag` values. For example, where there is currently 
```
controller:
  externalAttacher:
    image: registry.k8s.io/sig-storage/csi-attacher:v4.4.0
```
there would be 
```
controller:
  externalAttacher:
    image: registry.k8s.io/sig-storage/csi-attacher
    tag: v4.4.0
```
This would allow the image to be redirected to a different repo without having to override the tag as well.
