### ISSUE TITLE
Issue mount pv to pod

### ISSUE THREAD

**Issue by lzhengqc** [democratic-csi/charts#8]
I am able to install freenas-nfs-csi storage class. Testing claim created PV on NFS server. 

However, when trying to mount pvc to an pod, it times out. 

Here is the describe pv result 
**λ** kubectl describe pv pvc-a7b69c78-7875-4e2b-b4c4-4e7d909a9362
Name:            pvc-a7b69c78-7875-4e2b-b4c4-4e7d909a9362
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: org.democratic-csi.nfs
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    freenas-nfs-csi
Status:          Bound
Claim:           default/mongodb
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        8Gi
Node Affinity:   <none>
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            org.democratic-csi.nfs
    VolumeHandle:      pvc-a7b69c78-7875-4e2b-b4c4-4e7d909a9362
    ReadOnly:          false
    VolumeAttributes:      node_attach_driver=nfs
                           provisioner_driver=freenas-nfs
                           server=10.64.43.20
                           share=/mnt/pool0/k8s-dev/a/vols/pvc-a7b69c78-7875-4e2b-b4c4-4e7d909a9362
                           storage.kubernetes.io/csiProvisionerIdentity=1595572865963-8081-org.democratic-csi.nfs
Events:                <none>

Describe pod that is mounting has following events
Events:
  Type     Reason            Age        From                          Message
  ----     ------            ----       ----                          -------
  Warning  FailedScheduling  <unknown>  default-scheduler             error while running "VolumeBinding" filter plugin for pod "mongodb-7749784fc4-6t2s5": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler             error while running "VolumeBinding" filter plugin for pod "mongodb-7749784fc4-6t2s5": pod has unbound immediate PersistentVolumeClaims

**Comment by travisghansen** [comment]
Thanks for trying the project out!

That looks like a pretty odd error given the circumstances. Does the pod have another pvc? Can you confirm the dataset and share were properly created in FreeNAS?

If it’s a problem mounting the share then we’ll meed to get the logs from the ‘node’ pod running on the same node as the mongo pod has been assigned to.

I’m sure we’ll get you going.

**Comment by lzhengqc** [comment]
Yes, Pod does not have any other pvc. It is simple mongodb pod. PV is created and dataset is created in FreeNAS. I can see dataset in FreeNAS console. At the same time, I am able to mount the share from local computer. However, pod is not able to attach the PVC. 

 Here is the mongodb yaml for helm

```
mongodbRootPassword: rootpassword
mongodbUsername: user
mongodbPassword: password
mongodbDatabase: testdb
persistence:
  storageClass: freenas-nfs-csi
  accessMode: ReadWriteMany
service:
  type: NodePort
  nodePort: 30003
metrics:
  enabled: false

```

Here is freenas-nfs yaml configuration
```
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"

# add note here about volume expansion requirements
storageClasses:
- name: freenas-nfs-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: nfs
      
    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromSnapshots: "false"
    
    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromVolumes: "false"

  mountOptions:
  # - noatime
  # - nfsvers=3
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-nfs-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: 10.64.43.20
      port: 80
      username: root
      password: test
      allowInsecure: true
    sshConnection:
      host: 10.64.43.20
      port: 22
      username: root
      # use either password or key
      password: test
      # privateKey: |
      #   -----BEGIN RSA PRIVATE KEY-----
      #   ...
      #   -----END RSA PRIVATE KEY-----
    zfs:
      datasetParentName: pool0/k8s-dev/a/vols
      detachedSnapshotsDatasetParentName: pool0/k8s-dev/a/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: root
      datasetPermissionsGroup: wheel
    nfs:
      shareHost: 10.64.43.20
      shareAlldirs: true
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""
```
